name: AI Task Handler

on:
  # Trigger when an issue is labelled.  We only run when the `ai-task` label is added.
  issues:
    types: [labeled]

jobs:
  ai_task:
    if: github.event.label.name == 'ai-task'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    env:
      PYTHON_VERSION: '3.12'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install openai black ruff mypy pytest

      - name: Generate code from issue via Codex
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          python .github/scripts/codex_generate.py > generated_code.py

      - name: Create branch and commit generated code
        run: |
          BRANCH_NAME="ai/${{ github.event.issue.number }}"
          git config user.name "ai-bot"
          git config user.email "ai-bot@users.noreply.github.com"
          git checkout -b "$BRANCH_NAME"
          mkdir -p ai_tasks/${{ github.event.issue.number }}
          mv generated_code.py ai_tasks/${{ github.event.issue.number }}/main.py
          git add ai_tasks/${{ github.event.issue.number }}/main.py
          git commit -m "feat(ai): generate code for issue #${{ github.event.issue.number }}"
          git push origin "$BRANCH_NAME"

      - name: Run quality checks
        run: |
          make check

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GIT_TOKEN }}
          commit-message: "chore(ai): initial commit for issue #${{ github.event.issue.number }}"
          title: "AI task #${{ github.event.issue.number }}: ${{ github.event.issue.title }}"
          body: |
            This PR was automatically generated from issue #${{ github.event.issue.number }}.
          head: "ai/${{ github.event.issue.number }}"
          base: main
          labels: ai-generated
          draft: false
